// Données des fiches de la flotte Tranquility (aucune logique, aucun accès au DOM).
// Source des textes : maquette Lobby.dc.html validée.
// Ordre = ordre d'affichage du carrousel DÉCOUVRIR LA FLOTTE (D143/D153).
window.TranquilityFleet = Object.freeze([
  Object.freeze({
    id: 'backupflow',
    name: 'BackUpFlow',
    status: 'orbite',
    type: 'App Mac',
    hook: 'Tes rushes à l’abri partout, dès le retour de tournage.',
    body: 'Au retour de tournage, BackUpFlow copie et compresse tes rushes vers le NAS, deux SSD et le cloud, en une seule opération. Plus de copie à la main, plus de disque oublié. C’est l’app pionnière de la Suite, en service depuis février 2026.',
    forWho: 'Cellule Vidéo',
    motto: 'Nulla data pereunt',
    translation: 'Aucune donnée ne se perd.',
    mission: 'Copie sécurisée des rushes de tournage vers le NAS, le SSD et le cloud.',
    video: 'assets/patch-backupflow.mp4',
    poster: 'assets/patch-backupflow.png'
  }),
  Object.freeze({
    id: 'transporter',
    name: 'Transporter',
    status: 'orbite',
    type: 'App Mac',
    hook: 'Un projet Premiere qui voyage sans jamais perdre un média.',
    body: 'Transporter rassemble et range tous les fichiers d’un projet Premiere Pro dans une structure unique, toujours la même. Le projet passe d’un poste à l’autre, ou d’un monteur à l’autre, et s’ouvre partout sans média hors ligne.',
    forWho: 'Cellule Vidéo · Rédaction vidéo · DA / Studio',
    motto: 'Recte et celeriter',
    translation: 'Vite et bien.',
    mission: 'Organisation automatique des fichiers d’un projet Premiere Pro.',
    video: 'assets/patch-transporter.mp4',
    poster: 'assets/patch-transporter.png'
  }),
  Object.freeze({
    id: 'reviewer',
    name: 'Reviewer',
    status: 'orbite',
    type: 'App web',
    hook: 'Chaque montage relu, annoté et validé au timecode près.',
    body: 'Tu partages un montage, chacun le regarde dans son navigateur et laisse ses remarques pile au bon moment de la vidéo. Les retours ne se perdent plus dans les mails, et une vidéo ne part en ligne qu’une fois validée par les bonnes personnes.',
    forWho: 'Toutes les équipes',
    motto: 'Nihil nisi probatum',
    translation: 'Rien sans validation.',
    mission: 'Validation et annotation collaborative des montages vidéo.',
    video: 'assets/patch-reviewer.mp4',
    poster: 'assets/patch-reviewer.png'
  }),
  Object.freeze({
    id: 'manifest',
    name: 'Manifest',
    status: 'orbite',
    type: 'App web',
    hook: 'La feuille de service prête avant même que tu la demandes.',
    body: 'Le tournage est planifié dans Monday ? Manifest en tire une feuille de service complète et propre, prête à partager avec l’équipe. Aucune ressaisie, aucune version qui traîne.',
    forWho: 'Cellule Vidéo · DA / Studio · Opérations spéciales',
    motto: 'Ante omnia parare',
    translation: 'Préparer avant tout.',
    mission: 'Feuilles de service générées automatiquement depuis Monday.',
    video: 'assets/patch-manifest.mp4',
    poster: 'assets/patch-manifest.png'
  }),
  Object.freeze({
    id: 'ark',
    name: 'ARK',
    status: 'orbite',
    type: 'App Mac',
    hook: 'Tes projets livrés, archivés proprement pour les années à venir.',
    body: 'Une fois la vidéo livrée, ARK compresse les médias, emballe le projet complet dans une archive légère et met Monday à jour au passage. Le jour où il faut ressortir un sujet, tout est là, rangé au même endroit, de la même façon.',
    forWho: 'Cellule Vidéo · Rédaction vidéo',
    motto: 'Memoria manet',
    translation: 'La mémoire demeure.',
    mission: 'Archivage long terme des projets livrés.',
    video: 'assets/patch-ark.mp4',
    poster: 'assets/patch-ark.png'
  }),
  Object.freeze({
    id: 'rover',
    name: 'ROVER',
    status: 'orbite',
    type: 'App Mac',
    hook: 'La bonne référence vidéo, récupérée en un lien.',
    body: 'Colle un lien : ROVER télécharge la vidéo depuis plus de mille plateformes, dans le bon format, et la range directement au bon endroit. Fini les convertisseurs douteux et les fichiers perdus dans le dossier Téléchargements.',
    forWho: 'Cellule Vidéo · Rédaction vidéo · DA / Studio',
    motto: 'Explora et refer',
    translation: 'Explore et rapporte.',
    mission: 'Téléchargement de références vidéo depuis plus de mille plateformes.',
    video: 'assets/patch-rover.mp4',
    poster: 'assets/patch-rover.png'
  }),
  Object.freeze({
    id: 'covenant',
    name: 'COVENANT',
    status: 'orbite',
    type: 'App web',
    hook: 'Les autorisations de tournage signées sur place, au doigt.',
    body: 'Sur le terrain, la personne filmée signe son autorisation de droit à l’image directement sur ton téléphone ou ta tablette. Le document part aussitôt au bon destinataire, avec une copie au responsable. Plus de papier égaré, plus de signature à courir après.',
    forWho: 'Cellule Vidéo · Rédaction vidéo · Réseaux sociaux et 3 autres équipes',
    motto: 'Scripta manent',
    translation: 'Les écrits restent.',
    mission: 'Signature et validation des autorisations de tournage.',
    video: 'assets/patch-covenant.mp4',
    poster: 'assets/patch-covenant.png'
  }),
  Object.freeze({
    id: 'codex',
    name: 'CODEX',
    status: 'orbite',
    type: 'App web',
    hook: 'Un script Word, deux documents prêts à tourner et à monter.',
    body: 'Dépose un script de la rédaction : CODEX en tire automatiquement le texte du prompteur et la fiche de post-production, chapitres et timecodes compris. La mise en forme se fait toute seule, sans rien retaper.',
    forWho: 'Rédaction vidéo · Cellule Vidéo',
    motto: 'Ex uno duo',
    translation: 'D’un seul, deux.',
    mission: 'Transforme un script Word en script prompteur et fiche post-prod.',
    video: 'assets/patch-codex.mp4',
    poster: 'assets/patch-codex.png'
  }),
  Object.freeze({
    id: 'readback',
    name: 'READBACK',
    status: 'preparation',
    type: 'Mac, iPad, iPhone',
    hook: 'Le téléprompteur de la Suite, en préparation.',
    body: 'Le script défile sur l’écran du présentateur, piloté depuis un autre appareil : un MacBook aux commandes, un iPad pour la lecture, et bientôt un iPhone en télécommande. Plusieurs scripts se préparent à l’avance et s’enchaînent pendant le tournage.',
    forWho: 'Bientôt disponible',
    motto: 'Ad verbum',
    translation: 'Mot pour mot.',
    mission: 'Téléprompteur multi-écrans : MacBook, iPad et iPhone.',
    video: null,
    poster: null
  })
]);
